services:

  postgres:
    image: pgvector/pgvector:pg15

    container_name: mini_rag_postgres

    environment:
      POSTGRES_USER: teddy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_rag_db

    ports:
      - "5555:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
